// src/config/visualizations.js
//
// The 13 visualization modes with Scientific Provenance Metadata.
// Provenance Types:
//   "measured"      - Direct multi-spectral telemetry (Sentinel-2, Landsat SR)
//   "modeled"       - Mathematically transformed / downscaled (HLS, TsHARP Thermal 10m)
//   "synthetic-demo"- Multi-sensor synthetic composite (SAR C-Band Radar + Optical)
//
export const VISUALIZATIONS = [
    {
        id: "gap_fill",
        label: "Gap-Fill",
        sub: "S2 + L8 fill",
        icon: "🧩",
        ramp: "rgb",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#0ea5e9", "#22d3ee"],
        provenance: "modeled",
        provenanceBadge: "📐 Modeled",
        citation: "Harmonized S2 + L8 Cloud-Gap Fill (Sentinel-2 Authoritative)",
        legend: null,
    },
    {
        id: "true_color",
        label: "True Color",
        sub: "Natural",
        icon: "🛰️",
        ramp: "rgb",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#0ea5e9", "#22d3ee"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Direct Multi-Spectral Reflectance (Bands Red, Green, Blue)",
        legend: null,
    },
    {
        id: "ndvi",
        label: "NDVI",
        sub: "Vegetation",
        icon: "🌿",
        ramp: "ndvi",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#22c55e", "#10b981"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Rouse et al. (1973) (NIR - Red) / (NIR + Red)",
        legend: { min: -0.2, max: 0.8, colors: ["#000080", "#fee090", "#1a9850"], unit: "" },
    },
    {
        id: "ndwi",
        label: "NDWI",
        sub: "Water",
        icon: "💧",
        ramp: "ndwi",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#0ea5e9", "#3b82f6"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "McFeeters (1996) (Green - NIR) / (Green + NIR)",
        legend: { min: -0.3, max: 0.5, colors: ["#fdae61", "#abd9e9", "#081d58"], unit: "" },
    },
    {
        id: "ndbi",
        label: "NDBI",
        sub: "Built-up",
        icon: "🏙️",
        ramp: "ndbi",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#a855f7", "#ec4899"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Zha et al. (2003) (SWIR1 - NIR) / (SWIR1 + NIR)",
        legend: { min: -0.3, max: 0.3, colors: ["#1a9850", "#ffffbf", "#d73027"], unit: "" },
    },
    {
        id: "false_color_nir",
        label: "NIR Composite",
        sub: "Vegetation",
        icon: "🌾",
        ramp: "nir",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#dc2626", "#f59e0b"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Standard False Color Infrared (Bands NIR, Red, Green)",
        legend: null,
    },
    {
        id: "false_color_swir",
        label: "SWIR Composite",
        sub: "Moisture",
        icon: "🏜️",
        ramp: "swir",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#7c2d12", "#dc2626"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Shortwave Infrared Moisture Composite (SWIR1, NIR, Red)",
        legend: null,
    },
    {
        id: "sci",
        label: "SCI",
        sub: "Scientific",
        icon: "🔬",
        ramp: "sci",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#0891b2", "#06b6d4"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Agriculture & Geology Composite (SWIR2, NIR, Blue)",
        legend: null,
    },
    {
        id: "lst",
        label: "LST",
        sub: "Temperature",
        icon: "🌡️",
        ramp: "thermal",
        fusion: true,
        timelapse: true,
        sensors: ["landsat"],
        accent: ["#ef4444", "#f97316"],
        provenance: "measured",
        provenanceBadge: "🛰️ Measured",
        citation: "Landsat 8/9 TIRS Band 10 Uncorrected Thermal Radiance",
        legend: { min: 15, max: 45, colors: ["#313695", "#fee090", "#d73027"], unit: "°C" },
    },
    {
        id: "harmonized_l8",
        label: "Harmonized",
        sub: "HLS-style",
        icon: "🌐",
        ramp: "rgb",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#7c3aed", "#06b6d4"],
        provenance: "modeled",
        provenanceBadge: "📐 Modeled",
        citation: "Claverie et al. (2018) Harmonized Landsat-Sentinel Bandpass",
        legend: null,
    },
    {
        id: "real_lst",
        label: "LST (real)",
        sub: "Per-pixel ε",
        icon: "🌡️",
        ramp: "thermal",
        fusion: true,
        timelapse: true,
        sensors: ["landsat"],
        accent: ["#dc2626", "#ea580c"],
        provenance: "modeled",
        provenanceBadge: "📐 Modeled",
        citation: "Sobrino et al. (2004) Per-pixel NDVI Emissivity Correction",
        legend: { min: 15, max: 45, colors: ["#313695", "#fee090", "#d73027"], unit: "°C" },
    },
    {
        id: "thermal_10m",
        label: "Thermal 10m",
        sub: "Super-Res 10m",
        icon: "🔥",
        ramp: "thermal",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#ef4444", "#f97316"],
        provenance: "modeled",
        provenanceBadge: "📐 Modeled",
        citation: "TsHARP / DisTrad 10m Spatial Downscaling Model (Agam et al. 2007)",
        legend: { min: 15, max: 45, colors: ["#313695", "#fee090", "#d73027"], unit: "°C" },
    },
    {
        id: "sar_optical",
        label: "SAR Radar",
        sub: "All-Weather",
        icon: "🌩️",
        ramp: "rgb",
        fusion: true,
        timelapse: true,
        sensors: ["sentinel", "landsat"],
        accent: ["#0284c7", "#38bdf8"],
        provenance: "synthetic-demo",
        provenanceBadge: "🧪 Demo",
        citation: "Sentinel-1 C-Band SAR Microwave Radar + Optical Fusion",
        legend: null,
    },
];

export const VISUALIZATIONS_BY_ID = Object.fromEntries(
    VISUALIZATIONS.map((v) => [v.id, v])
);

/** Returns the modes usable for a given platform selection. */
export function availableFor(platforms) {
    const set = new Set(platforms.filter((p) => p === "sentinel" || p === "landsat"));
    return VISUALIZATIONS.filter((v) => v.sensors.some((s) => set.has(s)));
}
